django/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

import core.urls
import user.urls


MEDIA_FILE_PATHS = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(user.urls, namespace='user')),
    path('', include(core.urls, namespace='core')),
] + MEDIA_FILE_PATHS


# deubg_toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

django/core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('movies', views.MovieList.as_view(), name='MovieList'),
    path('movies/<int:pk>', views.MovieDetail.as_view(), name='MovieDetail'),
    path('person/<int:pk>', views.PersonDetail.as_view(), name='PersonDetail'),
    path('movie/<int:movie_id>/vote', views.CreateVote.as_view(), name='CreateVote'),
    path('movie/<int:movie_id>/vote/<int:pk>', views.UpdateVote.as_view(), name='UpdateVote'),
    path('movie/<int:movie_id>/image/upload',
        views.MovieImageUpload.as_view(),
        name='MovieImageUpload'),
    path('movie/top', views.TopMovies.as_view(), name='TopMovies'),
]

django/core/models.py
from django.db import models
from django.conf import settings
from django.db.models.aggregates import Sum

from uuid import uuid4


def movie_directory_path_with_uuid(instance, filename):
    return '{}/{}'.format(instance.movie_id, uuid4())


class MovieImage(models.Model):
    # ImageField uses Pillow
    image = models.ImageField(upload_to=movie_directory_path_with_uuid)
    uploaded = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey('Movie', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class PersonManager(models.Manager):
    def all_with_prefetch_movies(self):
        qs = self.get_queryset()                        ## lazy method
        ## query in once
        return qs.prefetch_related('directed',          ## related name from model Movie to get
                                   'writing_credits',   ## relevant Movie which has this person
                                   'role_set__movie')   ## model Role field movie


class Person(models.Model):
    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140)
    born = models.DateField()
    died = models.DateField(null=True, blank=True)

    objects = PersonManager()       ## for prefetch_related

    class Meta:
        ordering = ('last_name', 'first_name')

    def __str__(self):
        if self.died:
            return '{}, {} ({}-{})'.format(
                self.last_name,
                self.first_name,
                self.born,
                self.died)
        return '{}, {} ({})'.format(
                self.last_name,
                self.first_name,
                self.born)


class MovieManager(models.Manager):
    def all_with_related_persons(self):
        qs = self.get_queryset()
        qs = qs.select_related('director')              # used when 1 to 1, e.g. FK
        qs = qs.prefetch_related('writers', 'actors')   # used when m to m
        return qs                                       # its own fields, not related_name

    def all_with_related_persons_and_score(self):
        qs = self.all_with_related_persons()
        qs = qs.annotate(score=Sum('vote__value'))      # queryset annotate, model__field
                                                        # -> add query expression, e.g. sum
        return qs

    def top_movies(self, limit=10):
        qs = self.get_queryset()
        qs = qs.annotate(vote_sum=Sum('vote__value'))
        qs = qs.exclude(vote_sum=None)
        qs = qs.order_by('-vote_sum')
        qs = qs[:limit]
        return qs


class Movie(models.Model):
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = {
        (NOT_RATED, 'NR - Not rated'),
        (RATED_G, 'G - General audiences'),
        (RATED_PG, 'PG - Parental guidance'),
        (RATED_R, 'R - Restricted'),
    }

    title = models.CharField(max_length=140)
    plot = models.TextField()
    year = models.PositiveIntegerField()

    ## django added method get_xxxx_display(), i.e. get_rating_display()
    ## if used in template, which need not ()
    rating = models.IntegerField(               
        choices=RATINGS,                        
        default=NOT_RATED,
    )
    runtime = models.PositiveIntegerField()
    website = models.URLField(blank=True)       ## varchar(200)
    director = models.ForeignKey(
                to='Person',
                null=True,
                on_delete=models.SET_NULL,      ## db: only set null to this if related person is removed
                related_name='directed',        ## used by model linked to, i.e. Person
                                                ## if not set, default name = movie_set, which
                                                ## confuses with other FK/M2M fields
                blank=True)
    writers = models.ManyToManyField(
                to='Person',
                related_name='writing_credits', ## if not set, default name = movie_set
                blank=True)
    actors = models.ManyToManyField(
                to='Person',
                through='Role',                 ## custom through model
                related_name='acting_credits',
                blank=True)

    objects = MovieManager()

    class Meta:
        ordering = ('-year', 'title')

    def __str__(self):
        return '{} ({})'.format(self.title, self.year)


## must place behind Movie & Person; otherwise error occurs during "makemigrations"
class Role(models.Model):
    '''
    This through model creates 4 RelatedManagers: 
        movie.actors --> related manager of Person
        person.acting_credits --> related manager of Movie
        movie.role_set and person.role_set --> related manager of Role
    '''
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=140)

    def __str__(self):
        return "{} {} {}".format(self.movie_id, self.person_id, self.name)

    class Meta:
        unique_together = ('movie', 'person', 'name')


class VoteManager(models.Manager):
    def get_vote_or_unsaved_blank_vote(self, movie, user):
        try:
            return Vote.objects.get(movie=movie, user=user)
        except Vote.DoesNotExist:
            # if not found, return a unsaved blank Vote object
            return Vote(movie=movie, user=user)


class Vote(models.Model):
    UP = 1
    DOWN = -1
    VALUE_CHOICES = (
        (UP, "UP",),
        (DOWN, "DOWN",),
    )

    value = models.SmallIntegerField(choices=VALUE_CHOICES)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    voted_on = models.DateTimeField(auto_now=True)

    objects = VoteManager()

    class Meta:
        unique_together = ('user', 'movie')

django/core/forms.py
from django import forms
from django.contrib.auth import get_user_model

from core.models import Vote, Movie, MovieImage


class VoteForm(forms.ModelForm):
    user = forms.ModelChoiceField(  widget=forms.HiddenInput, 
                                    queryset=get_user_model().objects.all(),
                                    disabled=True,      #ignore whatever it changes
                                )
    movie = forms.ModelChoiceField( widget=forms.HiddenInput,
                                    queryset=Movie.objects.all(),
                                    disabled=True
                                )
    value = forms.ChoiceField(  label='Vote',
                                widget=forms.RadioSelect,
                                choices=Vote.VALUE_CHOICES,
                            )
    class Meta:
        model = Vote
        fields = ('value', 'user', 'movie',)


class MovieImageForm(forms.ModelForm):
    # By default, field image will be provided in form (tag input type)

    movie = forms.ModelChoiceField( widget=forms.HiddenInput, 
                                    queryset=Movie.objects.all(),
                                    disabled=True,
                                )  
    user = forms.ModelChoiceField(  widget=forms.HiddenInput,
                                    queryset=get_user_model().objects.all(),
                                    disabled=True
                                )
    class Meta:
        model = MovieImage
        fields = ('image', 'user', 'movie')

django/core/views.py
import django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.core.exceptions import PermissionDenied
from django.core.cache import cache
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from core.models import Movie, Person, Vote
from core.forms import VoteForm, MovieImageForm
from core.mixins import CachePageVaryOnCookieMixin


# ListView: query all rows
class MovieList(ListView):
    model = Movie               ## default manager --> Movie.objects.all()
    ## default template name is "object_list.html" for ListView
    paginate_by = 10            ## template variable if using "is_paginated" in template

    # shall add this function when using pagination
    def get_context_data(self, **kwargs):
        ctx = super(MovieList, self).get_context_data(**kwargs)
        page = ctx['page_obj']
        paginator = ctx['paginator']
        ctx['page_is_first'] = (page.number == 1)
        ctx['page_is_last'] = (page.number == paginator.num_pages)
        return ctx


# DetailView: query single row
class MovieDetail(DetailView):
    #model = Movie
    #queryset = Movie.objects.all_with_related_persons()
    queryset = Movie.objects.all_with_related_persons_and_score()

    def movie_image_form(self):
        if self.request.user.is_authenticated:
            return MovieImageForm()
        return None

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['image_form'] = self.movie_image_form()     # show image

        # GET request
        # render create or update form depends on existing vote or not
        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_unsaved_blank_vote(
                            movie=self.object,
                            user=self.request.user
                        )
            if vote.id:
                vote_form_url = reverse('core:UpdateVote',
                                        kwargs={
                                            'movie_id': vote.movie.id,
                                            'pk': vote.id
                                        }
                                )
            else:
                vote_form_url = reverse('core:CreateVote',
                                        kwargs={
                                            'movie_id': self.object.id
                                        }
                                )
            vote_form = VoteForm(instance=vote)
            ctx['vote_form'] = vote_form
            ctx['vote_form_url'] = vote_form_url
        return ctx


class PersonDetail(CachePageVaryOnCookieMixin, DetailView):
    queryset = Person.objects.all_with_prefetch_movies()


# LoginRequiredMixin: allows logged in user only
class CreateVote(LoginRequiredMixin, CreateView):
    form_class = VoteForm

    def get_initial(self):
        '''
        initial values for GET request
        For VoteForm, which has disabled user & movie values
        '''
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs['movie_id']
        return initial

    def render_to_response(self, context, **response_kwargs):
        '''
        for CreateView: here is an HTTP redirect
        '''
        movie_id = context['object'].id
        movie_detail_url = reverse('core:MovieDetail',kwargs={'pk': movie_id})
        return redirect(to=movie_detail_url)

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse('core:MovieDetail', kwargs={'pk': movie_id})


class UpdateVote(LoginRequiredMixin, UpdateView):
    form_class = VoteForm
    queryset = Vote.objects.all()

    def get_object(self, queryset = None):
        '''
        check if Vote retrieved is logged in user's vote
        '''
        vote = super().get_object(queryset)
        user = self.request.user
        if vote.user != user:
            raise PermissionDenied("cannot change another user vote")
        return vote

    def render_to_response(self, context, **response_kwargs):
        '''
        for UpdateView: an HTTP redirect
        '''
        movie_id = context['object'].id
        movie_detail_url = reverse('core:MovieDetail', kwargs={'pk':movie_id})
        return redirect(to=movie_detail_url)

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse('core:MovieDetail', kwargs={'pk':movie_id})


class MovieImageUpload(LoginRequiredMixin, CreateView):
    form_class = MovieImageForm

    def get_initial(self):
        '''
        initial values for GET request
        For MovieImageForm, which has disabled user & movie values
        '''
        initial = super().get_initial()
        initial['user'] = self.request.user.id          
        initial['movie'] = self.kwargs['movie_id']
        return initial

    def render_to_response(self, context, **response_kwargs):
        movie_id = self.kwargs['movie_id']
        movie_detail_url = reverse('core:MovieDetail', kwargs={'pk':movie_id})
        return redirect(to=movie_detail_url)

    def get_success_url(self):
        movie_id = self.kwargs['movie_id']
        movie_detail_url = reverse('core:MovieDetail', kwargs={'pk':movie_id})
        return movie_detail_url


class TopMovies(ListView):
    template_name = 'core/top_movies_list.html'
    #queryset = Movie.objects.top_movies(limit=10)

    def get_queryset(self):
        limit = 10
        key = 'top_movies_%s' % limit
        cached_qs = cache.get(key)
        if cached_qs:
            ## check versions (maybe not compatible)
            same_django = cached_qs._django_version == django.get_version()
            if same_django:
                #print(key)             #shows "top_movies_10"
                #print(cached_qs)       #shows QuerySet, with 10 movies objs
                return cached_qs
        qs = Movie.objects.top_movies(limit=limit)
        cache.set(key, qs)
        return qs

django/core/templates/core/movie_detail.html
{% extends 'base.html' %}

{% block title %}
  {{ object.title }} - {{ block.super }}
{% endblock %}

{% block main %}
  <div class="col">
    <h1>{{ object }}</h1>
    <p class="lead">
      {{ object.plot }}
    </p>
  </div>
  <div class="col">
    <ul class="movie-image list-inline">
      {% for i in object.movieimage_set.all %}
        <li class="list-inline-item">
          <img src="{{ i.image.url }}">
        </li>
      {% endfor %}
    </ul>
</div>
  <div class="col">
    <p>Directed by
      {{ object.director }}</p>
    <!--slight different from book: loop over the writers-->
    <p>Written by
      <ul>
        {% for writer in object.writers.all %}
          <li>
            <a href="{% url 'core:PersonDetail' pk=writer.id %}">
              {{ writer }}</a>
          </li>
        {% empty %}
          <li>None</li>
        {% endfor %}
      </ul>
    </p>
    <p>Actors
      <ul>
        {% for credit in object.role_set.all %}
          <li>
            <a href="{% url 'core:PersonDetail' pk=credit.person.id %}">
              {{ credit.person }}</a>: 
              {{ credit.name }}
          </li>
        {% empty %}
          <li>None</li>
        {% endfor %}
      </ul>
    </p>
  </div>
{% endblock %}

{% block sidebar %}
  <div>
    This movie is rated:
    <span class="badge badge-primary">
      {{ object.get_rating_display }}
    </span>
  </div>
  <div>
    <p>
      Total score: {{ object.score|default_if_none:"TBD" }}
    </p>
  </div>
  {% if image_form %}
    <div>
      <p>Upload New Image</p>
      <form method='post'
              enctype="multipart/form-data"
              action="{% url 'core:MovieImageUpload' movie_id=object.id %}">
        {% csrf_token %}
        {{ image_form.as_p}}
        <p>
          <button class='btn btn-primary'>Upload</button>
        </p>
      </form>
    </div>
  {% endif %}
  <div>
    {% if vote_form %}
	  <form
	    method="post"
		  action="{{ vote_form_url }}" >
	    {% csrf_token %}
        {{ vote_form.as_p }}
	    <button class="badge badge-primary" >
	      Vote
	    </button>
	  </form>
	{% else %}
	  <p>Log in to vote for this movie</p>
	{% endif %}
  </div>
{% endblock %}

django/core/templates/core/movie_list.html
{% extends 'base.html' %}

{% block title %}
  All The Movies
{% endblock %}

{% block main %}
  <ul>
    {% for movie in object_list %}
      <li>
        <a href="{% url 'core:MovieDetail' pk=movie.id %}">
          {{ movie }}
        </a>
      </li>
    {% endfor %}
  </ul>
  {% if is_paginated %}
    <nav>
      <ul class="pagination">
        <li class="page-item">
          <a
            href="{% url 'core:MovieList' %}?page=1" class="page-link"
          >
            First
          </a>
        </li>
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a
              href="{% url 'core:MovieList' %}?page={{ page_obj.previous_page_number }}"
              class="page-link"
            >
              {{ page_obj.previous_page_number }}
            </a>
          </li>
        {% endif %}
        <li class="page-item active">
          <a
            href="{% url 'core:MovieList' %}?page={{ page_obj.number }}"
            class="page-link"
          >
            {{ page_obj.number }}
          </a>
        </li>
        {% if page_obj.has_next %}
          <li class="page-item">
            <a
              href="{% url 'core:MovieList' %}?page={{ page_obj.next_page_number }}"
              class="page-link"
            >
              {{ page_obj.next_page_number }}
            </a>
          </li>
        {% endif %}
        <li class="page-item">
          <a
            href="{% url 'core:MovieList' %}?page=last" class="page-link"
          >
            Last
          </a>
        </li>
      </ul>
    </nav>
  {% endif %}
{% endblock %}

django/core/templates/core/person_detail.html
{% extends 'base.html' %}

{% block title %}
  {{ object.first_name }}
  {{ object.last_name }}
{% endblock %}

{% block main %}
  <div class="col">
    <h1>{{ object }}</h1>
  </div>
  <p>Actor</p>
  <ul>
    <!--use "role_set" because it gets data from Role, not Movie-->
    {% for role in object.role_set.all %}
      <li>
        <a href="{% url 'core:MovieDetail' pk=role.movie.id %}">
          {{ role.movie }}
        </a>:
        {{ role.name }}
      </li>
    {% endfor %}
  </ul>
  <p>Writer</p>
  <ul>
    {% for movie in object.writing_credits.all %}
      <li>
        <a href="{% url 'core:MovieDetail' pk=movie.id %}">
          {{ movie }}
        </a>
      </li>
  </ul>
  <p>Director</p>
  <ul>
    {% for movie in object.directed.all %}
      <li>
        <a href="{% url 'core:MovieDetail' pk=movie.id %}">
          {{ movie }}
        </a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

django/core/templates/core/top_movies_list.html
{% extends 'base.html' %}
{% load cache %}

{% block title %}
  Top 10 Movies
{% endblock %}

{% block main %}
  <h1>Top 10 Movies</h1>
  {% cache 300 top10 %}
  <ol>
    {% for movie in object_list %}
      <li>
        <a href="{% url 'core:MovieDetail' pk=movie.id %}" >
          {{ movie }}
        </a>  
      </li>
    {% endfor %}
  </ol>
  {% endcache %}
{% endblock %}